In [4]:
! pip install pandas

In [1]:
import pandas as pd
import numpy as np


print(pd.__version__)



2.0.1


In [12]:
#list

a = [1,2,4,5]

a[1:3]
print(a)


b = [[1,3,4]
     ,[2,2,6]]
print(b)


print(b[0][0],b[0][2])

c = [10,'apple',True]

print(c)

np.array(c)

[1, 2, 4, 5]
[[1, 3, 4], [2, 2, 6]]
1 4
[10, 'apple', True]


array(['10', 'apple', 'True'], dtype='<U11')

In [25]:
# numpy

a = np.array([0,1,2,3,4],dtype = np.int8)
print('a = ', a)
print(type(a))
print(a.dtype,'\n')

print(a[2:])
# attribute
print(a.shape)
print(a.dtype)


a =  [0 1 2 3 4]
<class 'numpy.ndarray'>
int8 

[2 3 4]
(5,)
int8


In [26]:
2**8/2

128.0

In [34]:
print(list(range(1,6)))

array = np.array([range(i,i+2)for i in [1,4,7]])
print(array)

print(array.shape)
print(array.dtype)


[1, 2, 3, 4, 5]
[[1 2]
 [4 5]
 [7 8]]
(3, 2)
int32


In [35]:
a = np.array([0,1]) #vetor
b = np.array([[0,1]]) #matrix

print(a.shape,a)
print(b.shape,b)

(2,) [0 1]
(1, 2) [[0 1]]


In [41]:
print(np.eye(3,5),'\n')


# Identity matrix
print(np.identity(3))
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
np.zeros([3,4]) #리스트 []

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((3,5))*255 #튜플()

array([[255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255.]])

In [52]:
np.full((5,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [62]:
array = np.array([range(i,i+2)for i in [1,3]])
print(array)

np.array([[1,2],[3,4]])

print(list(range(1,7,2)))

print(np.arange(1,7,2))


[[1 2]
 [3 4]]
[1, 3, 5]
[1 3 5]


In [78]:
array = np.array([range(i,i+9,2)for i in [1,3]],dtype = np.int64)
# 배열 1 들어가거 1 부터 10까지 2씩 증가 3 들어가고 9까지 2씩 증가 
print(array)

print(array.shape)
print(array.dtype)

[[ 1  3  5  7  9]
 [ 3  5  7  9 11]]
(2, 5)
int64


In [83]:
a1 = np.arange(1,10,2)
a2 = np.arange(3,12,2)

a = np.array([a1,a2],np.int64)
print(a)
print(a.shape)
print(a.dtype)

[[ 1  3  5  7  9]
 [ 3  5  7  9 11]]
(2, 5)
int64


In [100]:
i = np.identity(5,np.int64)*2
print(i)

[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 2]]


In [131]:
arr = np.arange(12)

arr_3by4 = arr.reshape(-1,4)

print(arr)

print(arr_3by4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [132]:
arr_3by4 = arr.reshape(-1,4)

print(arr_3by4)
print(list(arr_3by4.flat))

print(arr_3by4.T)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [146]:
x= np.array([[[0],[1],[2]]])
print(x)
print(x.shape)
print(x.reshape(1,1,3))
print(x.reshape(3,1,1))


[[[0]
  [1]
  [2]]]
(1, 3, 1)
[[[0 1 2]]]
[[[0]]

 [[1]]

 [[2]]]


In [160]:
print(x)
x.squeeze().shape
print(x.squeeze(axis=0))
print(x.squeeze(axis=0).shape)
print(x.squeeze(axis=2))
print(x.squeeze(axis=2).shape)


[[[0]
  [1]
  [2]]]
[[0]
 [1]
 [2]]
(3, 1)
[[0 1 2]]
(1, 3)


In [167]:
# vstack 묶고 싶을때

a = np.array([1,2,3])
b = np.array([3,5,1])
c = np.array([1,2,1])

print(a,b,c) 

d = np.vstack([a,b,c])
print(d)


[1 2 3] [3 5 1] [1 2 1]
[[1 2 3]
 [3 5 1]
 [1 2 1]]


In [181]:
# 한배열에 합치기 

a = np.array([1,2,3])
b = np.array([3,5,1])



a= np.array([[1],[2],[3]])
b= np.array([[1],[2],[3]])

print(a)
print(b)

print('hstack = ',np.hstack([a,b]))
print('vstack = ',np.vstack([a,b]))


# d=np.hstack([a,b])

# print(d)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
hstack =  [[1 1]
 [2 2]
 [3 3]]
vstack =  [[1]
 [2]
 [3]
 [1]
 [2]
 [3]]


In [197]:
#column stack

a = np.arange(1,6)


b = np.arange(2,7)

print('hstack = ',np.hstack([a,b]))
print('vstack = ',np.vstack([a,b]))
# print('column = ',np.column([a,b]))

print(a)
print(b)

hstack =  [1 2 3 4 5 2 3 4 5 6]
vstack =  [[1 2 3 4 5]
 [2 3 4 5 6]]
[1 2 3 4 5]
[2 3 4 5 6]


In [198]:
A = [[1,2,3,4],[2,4,5,8]]
B = [6,6,5,4]

c = np.vstack([A,B])

print(c.T)


[[1 2 6]
 [2 4 6]
 [3 5 5]
 [4 8 4]]


In [260]:
# Random sampling

# Uniform (균일분포) ,integer unifrom, Gaussian 분포 (정규분표)


# Uniform (균일분포)
np.random.rand(256,256)

array([[0.17547364, 0.12626487, 0.23810329, ..., 0.53236172, 0.65290364,
        0.46668712],
       [0.40794518, 0.64402647, 0.78194362, ..., 0.26663207, 0.30767218,
        0.32136442],
       [0.53785953, 0.11916895, 0.02073976, ..., 0.75545773, 0.20397364,
        0.1817198 ],
       ...,
       [0.24621018, 0.99149571, 0.97721365, ..., 0.02060518, 0.84982647,
        0.36918884],
       [0.73254793, 0.82411665, 0.61228214, ..., 0.86644851, 0.12155455,
        0.756435  ],
       [0.11661159, 0.51068025, 0.8652069 , ..., 0.76442096, 0.71172613,
        0.02121655]])

In [340]:
np.random.randint(1,10,(3,2))

array([[2, 7],
       [5, 9],
       [7, 5]])

In [386]:
# np.random.seed(503)
# np.random.randn(100)
np.random.normal(172,3,(3,3))


array([[166.62478047, 174.72572638, 171.10839055],
       [171.86379648, 171.86958907, 175.20471618],
       [169.67524542, 176.07343932, 173.55534353]])

In [393]:
a= np.arange(1,10,2)
print(a)

print(a.mean())

print(np.median(a))

b = np.random.normal(10,3,20)
print(b.mean())

print(np.median(b))


[1 3 5 7 9]
5.0
5.0
8.459093057147467
7.685364440404802


In [401]:
a = np.array([[1,2],[3,4]])
print(a)
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[[1 2]
 [3 4]]
[2. 3.]
[1.5 3.5]


In [402]:
print(np.var(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

1.25
1.118033988749895
1
4


In [32]:
a= np.array([1,2,3,5])
b= np.array([4,5,6,2])
c= np.array([4,4,6,3])

A = np.vstack([a,b,c])

print(A)
print(A.shape)
print(a.dtype)

[[1 2 3 5]
 [4 5 6 2]
 [4 4 6 3]]
(3, 4)
int32


In [36]:
# # row indexing
# print(A[0])
# print(A[1])
# print(A[2])

# # colum indexing
# print(A[:,0])
# print(A[:,1])
# print(A[:,2])
# print(A[:,3])

# # row and colum indexing
# print(A[0:2,1:])

# Fancy inexing 가로 행0,세로 열1 가로 행2,세로 열3이 뽑힌다

print(A[[0,2],
        [1,3]])

[2 3]
